# Generated by Django 2.2.1 on 2019-10-15 22:14

import account.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191016_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validity',
            field=models.DateTimeField(default=account.helpers.DefaultPeriod()),
        ),
    ]
