# Generated by Django 2.2.1 on 2019-10-03 21:47

import account.helpers
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nicname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='m', max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('weblinks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, size=None)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('magazine', 'Magazine'), ('other', 'Other')], default='other', max_length=20)),
                ('accession_number', models.CharField(max_length=50)),
                ('call_number', models.CharField(max_length=20)),
                ('copy_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('mrp', models.PositiveIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='resource/resource/image/default.png', height_field='height_field', null=True, upload_to=account.helpers.UploadTo('image'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('work_done', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(to='academic.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('pagination', models.PositiveIntegerField(blank=True, null=True)),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('call_number', models.CharField(max_length=20)),
                ('copy_number', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=20)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('last_revision_date', models.DateField(blank=True, null=True)),
                ('mrp', models.PositiveIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='resource/book/image/default.png', height_field='height_field', null=True, upload_to=account.helpers.UploadTo('image'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('work_done', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author', models.ManyToManyField(to='resource.Author')),
                ('departments', models.ManyToManyField(to='academic.Department')),
            ],
        ),
    ]
