# Generated by Django 2.2.1 on 2020-03-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'nicname']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'call_number']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['title', 'call_number']},
        ),
    ]
