# Generated by Django 2.2.1 on 2020-03-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20200307_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=15, null=True),
        ),
    ]
