# Generated by Django 2.2.1 on 2020-03-14 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20200314_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
