# Generated by Django 2.2.1 on 2020-03-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dept_id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['faculty_id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['program_id', 'name']},
        ),
    ]
